### ISSUE TITLE
Add "add to calendar" button

### ISSUE THREAD

**Issue by mattstratton** [Irreverent-DevOps/irreverentdevops-web#15]
I haven't quite thought through exactly where this goes; in theory you would have a main "add to calendar" on the main page that is the next episode, but also have one on the episode page

**Comment by mattstratton** [comment]
there's a way to do this if we make the event in google calendar and then you "publish event"; this makes a link or something?

**Comment by mattstratton** [comment]
more info: https://support.google.com/calendar/answer/41207?hl=en

**Comment by mattstratton** [comment]
fyi I've been doing this "by hand" but eventually when we have some kind of more data-driven thing for the episodes, there could be a data field that is the link or whatever for it

**Comment by nimbinatus** [comment]
(sorry! The data driven version is coming!)

**Comment by mattstratton** [comment]
Dupe of #89
