### ISSUE TITLE
Google analytics?

### ISSUE THREAD

**Issue by mattstratton** [Irreverent-DevOps/irreverentdevops-web#17]
what it says on the tin

**Comment by jerdog** [comment]
I don't see why not - but I believe Netlify has something - let me have a check

**Comment by mattstratton** [comment]
I actually like Netlify's stats better than GA, but they aren't free IIRC

**Comment by jerdog** [comment]
Ahh - it's $9/mo for Netlify Analytics.... That's a nope. =)
