### ISSUE TITLE
Update open graph tags

### ISSUE THREAD

**Issue by mattstratton** [Irreverent-DevOps/irreverentdevops-web#9]
We should set OG tags for preview image, etc.

Not sure what image we want; in theory we could use the one for the upcoming episode, but twitter, etc, will cache.

So we want an image per episode, which would be the image OG tag for the episode page, and then a more generic one for the main site, etc.

This is low priority.

**Comment by mattstratton** [comment]
I think there is some helpful stuff here too https://medium.com/yellowcode/how-to-do-meta-tags-in-gatsbyjs-45245dc68ab9

IIRC this isn't quite custom enough for the end state but maybe it is okay (depends on if we want to have custom OG images per epsiode, for example)

**Comment by jerdog** [comment]
Yeah seeing a few things as well:

https://juliangaramendy.dev/custom-open-graph-images-in-gatsby-blog/
https://www.gatsbyjs.org/docs/add-seo-component/

And an actual plugin which might do it for us

https://www.gatsbyjs.org/packages/gatsby-plugin-next-seo/

**Comment by mattstratton** [comment]
the article I linked has some tips/ideas for favicon too which I liked :)

**Comment by mattstratton** [comment]
that plugin is the jam for sure - it handles what I wanted with having per-page stuff and that seems pretty straightforward. I vote for trying the plugin.

**Comment by mattstratton** [comment]
I looked at the plugin a little more, and it's too opinionated about a couple things that bug me.

I think that https://juliangaramendy.dev/custom-open-graph-images-in-gatsby-blog/ has what I need to reverse-engineer all the other stuff I like :)

**Comment by jerdog** [comment]
heh go for it - we don't have some of the stuff they mention already (like an seo.js component)

**Comment by mattstratton** [comment]
This is mostly working - I don't want to close this until I feel like it's better and optimal, but it's sorta there :)

**Comment by mattstratton** [comment]
I'm going to close this one since #86 is tracking more currently
